### ISSUE TITLE
Open API Missing BaseSAMLv2ApplicationConfiguration when building

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-openapi#2]
Open API Missing BaseSAMLv2ApplicationConfiguration when building

Examples from autorest and openapi-client below.

```
(test) ➜  openapi-client git:(fusionauth-openapi) ✗ autorest --input-file=../../openapi/fusionauth.yaml --python  --namespace=fusionauth 
AutoRest code generation utility [cli version: 3.6.3; node: v18.14.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ^3.7.0.
info    |    Loading AutoRest core      '/Users/richard/.autorest/@autorestcore@3.9.4/nodemodules/@autorest/core/dist' (3.9.4)
info    |    Installing AutoRest extension '@autorest/python' (latest -> 6.4.0)
installing... [========================================] 100% | 16/16
info    |    Installed AutoRest extension '@autorest/python' (latest->6.4.0)
info    |    Loading AutoRest extension '@autorest/modelerfour' (~4.23.5->4.23.7)
error   | InvalidRef | Ref '#/components/schemas/BaseSAMLv2ApplicationConfiguration' is not referencing a valid location. components,schemas,BaseSAMLv2IdentityProvider,properties,applicationConfiguration,additionalProperties
    - file:///Users/richard/dev/authentication-service/openapi/fusionauth.yaml:6873:11
fatal   | Plugin 'full-ref-resolver' completed with some error.
error   |   Error: Plugin 'full-ref-resolver' completed with some error.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
```

Openapi-generator

```
(test) ➜  openapi-client git:(fusionauth-openapi) ✗ openapi-generator generate -i ../../openapi/fusionauth.yaml -g python -c fusionauth.config.yaml 
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 131
Errors: 
        -attribute components.schemas.BaseSAMLv2IdentityProvider.BaseSAMLv2ApplicationConfiguration is not of type `schema`
Warnings: 
        -attribute components.schemas.BaseSAMLv2IdentityProvider.BaseSAMLv2ApplicationConfiguration is not of type `schema`

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:620)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:647)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:465)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

Internal -> tickets - 73173

**Comment by mooreds** [comment]
This was fixed under https://github.com/FusionAuth/fusionauth-client-builder/pull/67 which excludes the abstract class from the openapi components. 

Closing.
